Filminurk/Models/FavouriteLists/FavouriteListIndexImageViewModel.cs
namespace Filminurk.Models.FavouriteLists
{
    public class FavouriteListIndexImageViewModel
    {
        public Guid ImageID { get; set; }
        public string ImageTitle { get; set; }
        public byte[] ImageData { get; set; }
        public string Image {  get; set; }
        public Guid? ListID { get; set; }
    }
}

Filminurk/Models/FavouriteLists/FavouriteListIndexViewModel.cs
namespace Filminurk.Models.FavouriteLists
{
    public class FavouriteListIndexViewModel
    {
        public Guid ImageID { get; set; }
        public string ImageTitle { get; set; }
        public byte[] ImageData { get; set; }
        public string Image {  get; set; }
        public Guid? ListID { get; set; }
    }
}

Filminurk/Models/FavouriteLists/FavouriteListUserCreateViewModel.cs
using Filminurk.Core.Domain;

namespace Filminurk.Models.FavouriteLists
{
    public class FavouriteListUserCreateViewModel
    {
        public Guid? FavouriteListID { get; set; }
        public string ListsBelongsToUser { get; set; }
        public bool IsMovieOrActor { get; set; }
        public string ListName { get; set; }
        public string? ListDescription { get; set; }
        public bool IsPrivate { get; set; }
        public List<Movie>? ListOfMovies { get; set; }
        public DateTime? ListCreatedAt { get; set; }
        public DateTime? ListModifiedAt { get; set; }
        public DateTime? ListDeletedAt { get; set; }
        public bool IsReported { get; set; } = false;
        public List<FavouriteListIndexImageViewModel> Images { get; set; } = new List<FavouriteListIndexImageViewModel>();
    }
}

Filminurk/Models/FavouriteLists/FavouriteListUserDetailsViewModel.cs
using Filminurk.Core.Domain;

namespace Filminurk.Models.FavouriteLists
{
    public class FavouriteListUserDetailsViewModel
    {
        public Guid? FavouriteListID { get; set; }
        public string ListsBelongsToUser { get; set; }
        public bool IsMovieOrActor { get; set; }
        public string ListName { get; set; }
        public string? ListDescription { get; set; }
        public bool IsPrivate { get; set; }
        public List<Movie>? ListOfMovies { get; set; }
        public DateTime? ListCreatedAt { get; set; }
        public DateTime? ListModifiedAt { get; set; }
        public DateTime? ListDeletedAt { get; set; }
        public bool IsReported { get; set; } = false;
        //public FavouriteListIndexImageViewModel Images { get; set; } = new FavouriteListIndexImageViewModel();
    }
}

Filminurk/Models/FavouriteLists/FavouriteListsIndexViewModel.cs
using Filminurk.Core.Domain;

namespace Filminurk.Models.FavouriteLists
{
    public class FavouriteListsIndexViewModel
    {
        public Guid FavouriteListID { get; set; }
        public string ListsBelongsToUser { get; set; }
        public bool IsMovieOrActor { get; set; }
        public string ListName { get; set; }
        public string? ListDescription { get; set; }
        public bool IsPrivate { get; set; }
        public List<Movie>? ListOfMovies { get; set; }
        public DateTime? ListCreatedAt { get; set; }
        public DateTime? ListModifiedAt { get; set; }
        public DateTime? ListDeletedAt { get; set; }
        public bool IsReported { get; set; } = false;
        public List<FavouriteListIndexImageViewModel> Images { get; set; } = new List<FavouriteListIndexImageViewModel>();
    }
}

Filminurk/Controllers/FavouriteListsController.cs
using System.Security.Cryptography.Xml;
using Filminurk.Core.Domain;
using Filminurk.Core.Dto;
using Filminurk.Core.ServiceInterface;
using Filminurk.Data;
using Filminurk.Models;
using Filminurk.Models.FavouriteLists;
using Filminurk.Models.Movies;
using Microsoft.AspNetCore.Mvc;

namespace Filminurk.Controllers
{
    public class FavouriteListsController : Controller
    {
        private readonly FilminurkTARpe24Context _context;
        private readonly IFavouriteListsServices _favouriteListsServices;
        public FavouriteListsController(FilminurkTARpe24Context context,
            IFavouriteListsServices favouriteListsServices)
        {
            _context = context;
            _favouriteListsServices = favouriteListsServices;
        }
        public IActionResult Index()
        {
            var resultingLists = _context.FavouriteLists
                .OrderByDescending(y => y.ListCreatedAt)
                .Select(x => new FavouriteListsIndexViewModel
                {
                    FavouriteListID = x.FavouriteListID,
                    ListsBelongsToUser = x.ListsBelongsToUser,
                    IsMovieOrActor = x.IsMovieOrActor,
                    ListName = x.ListName,
                    ListDescription = x.ListDescription,
                    ListCreatedAt = x.ListCreatedAt,
                    Images = (List<FavouriteListIndexImageViewModel>)_context.FilesToDatabase
                   .Where(ml => ml.ListID == x.FavouriteListID)
                   .Select(Li => new FavouriteListIndexImageViewModel
                   {
                       ListID = Li.ListID,
                       ImageData = Li.ImageData,
                       ImageTitle = Li.ImageTitle,
                       Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(Li.ImageData)),
                       ImageID = Li.ImageID,
                   })


                }

                );

            return View(resultingLists);

        }
        [HttpGet]
        public IActionResult Create()
        {
            var movies = _context.Movies
                .OrderBy(m => m.Title)
                .Select(mo => new MoviesIndexViewModel
                {
                    ID = mo.ID,
                    Title = mo.Title,
                    FirstPublished = mo.FirstPublished,
                    CurrentRating = mo.CurrentRating,
                })
                .ToList();
            ViewData["allmovies"] = movies;
            ViewData["iserHasSelected"] = new List<string>();
            FavouriteListUserCreateViewModel vm = new();
            return View("UserCreate", vm);
        }
        [HttpPost]
        public async Task<IActionResult> UserCreate(FavouriteListUserCreateViewModel vm, List<string> userHasSelected,
            List<MoviesIndexViewModel> movies)
        {
            List<Guid> tempParse = new();
            foreach (var stringID in userHasSelected)
            {
                tempParse.Add(Guid.Parse(stringID));
            }
            var newListDto = new FavouriteListDTO() { };
            newListDto.ListName = vm.ListName;
            newListDto.ListDescription = vm.ListDescription;
            newListDto.IsMovieOrActor = vm.IsMovieOrActor;
            newListDto.IsPrivate = vm.IsPrivate;
            newListDto.ListCreatedAt = DateTime.UtcNow;
            newListDto.ListsBelongsToUser = "00000000-0000-0000-000000000001";
            newListDto.ListDeletedAt = vm.ListDeletedAt;
            newListDto.ListOfMovies = vm.ListOfMovies;

            foreach(var movieId in tempParse)
            {
                var thismovie = _context.Movies.Where(tm => tm.ID == movieId).ToList().Take(1);
                newListDto.ListOfMovies.Add((Movie)thismovie);
            }
            //List<Guid> convertedIDs = new List<Guid>();
            //if (newListDto.ListOfMovies != null)
            //{
            //    convertedIDs = MovieToId(newListDto.ListOfMovies);
            //}

            var newList = await _favouriteListsServices.Create(newListDto /*, convertedIDs*/);
            if (newList != null)
            {
                return BadRequest();
            }
            return RedirectToAction("Index", vm);
        }
        [HttpGet]
        public async Task<IActionResult> UserDetails(Guid id, Guid thisuserid)
        {
            if(id == null || thisuserid == null)
            {
                return BadRequest();
            }
            var thisList = _context.FavouriteLists
                .Where(tl => tl.FavouriteListID == id && tl.ListsBelongsToUser ==
                thisuserid.ToString())
                .Select(
                stl => new FavouriteListUserDetailsViewModel
                {
                    FavouriteListID = stl.FavouriteListID,
                    ListsBelongsToUser = stl.ListsBelongsToUser,
                    ListName = stl.ListName,
                    ListDescription = stl.ListDescription,
                    IsPrivate = stl.IsPrivate,
                    ListOfMovies = stl.ListOfMovies,
                    IsReported = stl.IsReported,
                //    Images = _context.FilesToDatabase
                //    .Where(i => i.ListID == stl.FavouriteListID)
                //    .Select(si => new FavouriteListIndexImageViewModel
                //    {
                //        ImageID = si.ImageID,
                //        ListID = si.ListID,
                //        ImageData = si.ImageData,
                //        ImageTitle = si.ImageTitle,
                //        Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(si.ImageData))
                //    }
                //    ).ToList().First()

                //}
                //);
            
            if(thisList == null)
            {
                return NotFound();
            }
            return View("Details", thisList.First());

        }
        [HttpPost]
        public async Task<IActionResult>  UserTogglePrivacy(Guid id)
        {
            FavouriteList thisList = _favouriteListsServices.DetailsAsync(id);
            FavouriteListDTO updatedList = new FavouriteListDTO();
            updatedList.FavouriteListID = thisList.FavouriteListID;
            updatedList.ListsBelongsToUser = thisList.ListsBelongsToUser;
            updatedList.ListName = thisList.ListName;
            updatedList.ListDescription = thisList.ListDescription;
            updatedList.IsPrivate = thisList.IsPrivate;
            updatedList.ListOfMovies = thisList.ListOfMovies;
            updatedList.IsReported = thisList.IsReported;
            updatedList.IsMovieOrActor = thisList.IsMovieOrActor;
            updatedList.ListCreatedAt = thisList.ListCreatedAt;
            updatedList.ListModifiedAt = DateTime.Now;
            updatedList.ListDeletedAt = DateTime.Now;

            var result = await _favouriteListsServices.Update(updatedList);
            if(result == null)
            {
                return NotFound();
            }
            if(result == null || result.IsPrivate != !result.IsPrivate)
            {
              return BadRequest();
            }
           
            //return View("Details", updatedList);
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> UserDelete(Guid id)
        {
            var deletedList = await _favouriteListsServices.DetailsAsync(id);
            deletedList.ListDeletedAt = DateTime.Now;
            var dto = new FavouriteListDTO();
            dto.FavouriteListID = deletedList.FavouriteListID;

            dto.ListsBelongsToUser = deletedList.ListsBelongsToUser;
            dto.ListName = deletedList.ListName;
            dto.ListDescription = deletedList.ListDescription;
            dto.IsPrivate = deletedList.IsPrivate;
            dto.ListOfMovies = deletedList.ListOfMovies;
            dto.IsReported = deletedList.IsReported;
            dto.IsMovieOrActor = deletedList.IsMovieOrActor;
            dto.ListCreatedAt = deletedList.ListCreatedAt;
            dto.ListModifiedAt = DateTime.Now;
            dto.ListDeletedAt = deletedList.ListDeletedAt;
            



            var result = await _favouriteListsServices.Update(deletedList);
        }
        private List<Guid> MovieToId(List<Movie> listOfMovies)
        {
            var result = new List<Guid>();
            foreach (var movie in listOfMovies)
            {
                result.Add(movie.ID);
            }
            return result;
        }
    }
}

Filminurk/Views/FavouriteLists/Details.cshtml
@model Filminurk.Models.FavouriteLists.FavouriteListUserDetailsViewModel
@{
	int rowNumber = 1;
}
´<div>
	@if(Model.IsReported == true)
	{
		@:Sinu nimekiri rikub kogukonna reegleid<br />
		@:Oleme seadnud nimekirja privaatseks kuni admin selle üle vaatab.<br />
	}
	<table>
		<tr>@Model.ListName</tr>
		<tr>@* <partial name="_ImageIndex" model="@Model.Images"> *@</partial></tr>
		<tr>@Model.IsPrivate</tr>
	</table>
</div>
<div>
	<form method="post">
	<table class="table">

	
	@foreach(var movie in Model.ListOfMovies)
	{
		<tr>
			<table class="table" style="border:thick;">
				<tr>
					<td colspan="2">
						@movie.Title
					</td>
				</tr>
				<tr>
						<td>(Image here)</td>
						<td>
							<table>
								<tr>@movie.Description</tr>
								<tr>@movie.Director</tr>
								<tr>@movie.IMDbRating</tr>
								<tr>@movie.OscarsWon</tr>
							</table>
						</td>
				</tr>
			</table>
		</tr>
	}
	</table>
	<div>
		<input asp-action="UserDelete" asp-controller="FavouriteListsController" asp-route-id="@Model.FavouriteListID"
		type="submit" class="btn btn-danger" value="Kustuta Nimekiri"/>

		<input asp-action="UserTogglePrivacy" asp-controller="FavouriteListsController" asp-route-id="@Model.FavouriteListID"
			   type="submit" class="btn btn-warning" value="Muuda nimekiri privaatseks" />

		<input asp-action="UserEditList" asp-controller="FavouriteListsController" asp-route-id="@Model.FavouriteListID"
			   type="submit" class="btn btn-success" value="Muuda nimekirja sisu ja andmeid" />

		<a asp-action="Index" asp-controller="FavouriteListsController" class="btn btn-light">Tagasi</a>
			   



	</div>
	
	</form>
</div>

Filminurk/Views/FavouriteLists/Index.cshtml
@model  IEnumerable<Filminurk.Models.FavouriteLists.FavouriteListsIndexViewModel>
@{
	int rowNumber = 1;
	int currentRow = 1;
	int currentTile = 1;
	int tilesInRow = 1;
}
<div>
	<a asp-action="CreateList" asp-controller="FavouriteLists" class="btn btn-primary">Tee uus lemmikute nimikiri</a>
	<a asp-action="Index" asp-controller="Home" class="btn btn-primary">Pealeht</a>
</div>
<div>
	<form method="post">
		<table class="table">
			<thead>
				@if (!Model.Any()){

					<tr>
						<th scope="col" colspan="2">
							<span>Kahjuks ei leidnud ühtegi lemmikute nimekirja.</span>
						</th>
					</tr>
				}
				else{
					<tr>
						<th scope="col" colspan="2">
							<span>Sinu nimekirjad:</span>
						</th>
					</tr>

				}
			</thead>
			<tbody>
				@if (!Model.Any()){

					<table>
						<tr>
							<td colspan="2">Sorry, no list</td>
						</tr>
						<tr>
							<td colspan="2"><img width="128" src="ˇ~/lib/defaultassets/image/noposter.png"/></td>
						</tr>
					</table>
				}
				else
				{
					@foreach(var list  in Model)
					{
						<table>
							<tr>
								<td colspan="2">
									
									<a asp-action="ListDetailsListOwner" asp-controller="FavouriteLists" asp-route-id="@list.FavouriteListID"
									 asp-route-thisuserid="@list.ListsBelongsToUser">@list.ListName</a>
									
									
								</td>
							</tr>
							<tr>
								<td>
									@foreach(var image in list.Images)
									{
										<partial name="_ImageIndex" model="image" />
									}
								</td>
								<td>@list.ListDescription</td>
							</tr>
						</table>
					}
					rowNumber++;
				}
			</tbody>
		</table>
	</form>

</div>

Filminurk/Views/FavouriteLists/UserCreate.cshtml
@model Filminurk.Models.FavouriteLists.FavouriteListUserCreateViewModel
@{
	var allMoviesTickboxes = ViewData["allmovies"] as List<Filminurk.Models.Movies.MoviesIndexViewModel>;
	List<string> userHasSelected = ViewBag.userHasSelected;
	List<string> prevouslySelected = userHasSelected;
}
<h1>Tee uus nimekiri</h1>
<div>
	<form method="post" enctype="multipart/form-data">
		<input asp-for="FavouriteListID" type="hidden" />
		<input asp-for="ListCreatedAt" type="hidden" />
		<input asp-for="ListModifiedAt" type="hidden" />
		<input asp-for="ListDeletedAt" type="hidden" />
		<input asp-for="IsReported" type="hidden" />
		<input asp-for="ListsBelongsToUser" type="hidden" />
		<div class="form-group-row">
			<label asp-for="ListName" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="ListName" class="form-control" />
			</div>
		</div>
		<div class="form-group-row">
			<label asp-for="ListDescription" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="ListDescription" class="form-control" />
			</div>
		</div>
		<div class="form-group-row">
			<label asp-for="IsPrivate" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input type="checkbox" asp-for="IsPrivate" class="form-control" />
			</div>
		</div>
		@if (allMoviesTickboxes == null)
		{
			<tr>Filme andmebaasis</tr>
		}
		else{

			@foreach(var movie in allMoviesTickboxes)
			{
				<tr>
					<td>@movie.Title</td>
					<td>@movie.FirstPublished</td>
					
					<td>
						@if(movie.ID.HasValue)
						{
							<input
							type="checkbox"
							name="userHasSelected"
							value="@movie.ID"
							id="checkbox-@movie.ID"
							@if(userHasSelected.Contains(movie.ID.ToString()))
							{
								@:checked
							}
							/>
						}
						else
						{
							
							<input type="checkbox" name="userHasSelected" value="@movie.ID" id="checkbox-@movie.ID" />
						}
					</td>
			</tr>
		}
		}
		<input
			asp-action="UserCreate"
			asp-controller="FavouriteLists"
			type="submit"
			class="btn btn-primary"
			value="Tee Nimekiri"
			/>


	</form>
</div>

Filminurk/Views/FavouriteLists/_ImageIndex.cshtml
@model Filminurk.Models.FavouriteLists.FavouriteListIndexImageViewModel
<div>
	@if (!Model.Image.Any())
	{
		<p>Cannot find images</p>
	}
</div>
@if(Model.ImageTitle == "Poster")
{
	<img class="card-img-top" src="@Model.Image" asp-append-version="true"/>
}
else
{
	<img width="128" src="ˇ~/lib/defaultassets/image/noposter.png" />
}