Filminurk/Models/UserComments/UserCommentsIndexViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Filminurk.Models.UserComments
{
    public class UserCommentsIndexViewModel
    {
        [Key]
        public Guid CommentID { get; set; }
        public string? CommenteryUserID { get; set; }
        public string CommentBody { get; set; }
        public int? CommentedScore { get; set; }
        public int? IsHelpful { get; set; }
        public int IsHarmful { get; set; }

        public DateTime CommentCreatedAt { get; set; }
        public DateTime? CommentModifiedAt { get; set; }
        public DateTime? CommentDeletedAt { get; set; }
    }
}

Filminurk/Controllers/UserCommentsController.cs
using Filminurk.Data;
using Filminurk.Models.UserComments;
using Microsoft.AspNetCore.Mvc;

namespace Filminurk.Controllers
{
    public class UserCommentsController : Controller
    {
        private readonly FilminurkTARpe24Context _context;
        public UserCommentsController(FilminurkTARpe24Context context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var result = _context.UserComments
                .Select(d => new UserCommentsIndexViewModel
                {
                    CommentID = d.CommentID,
                    CommentBody = d.CommentBody,
                    IsHarmful = (int)d.IsHarmful,
                    CommentCreatedAt = d.CommentCreatedAt,

                });
            return View(result);
        }
    }
}

Filminurk/Views/UserComments/DeleteAdmin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Filminurk/Views/UserComments/Index.cshtml
@model IEnumerable<Filminurk.Models.UserComments.UserCommentsIndexViewModel>
@{
	int rowNumber = 1;
}
<div>
	<a asp-action="NewComment" asp-controller="UserComments" type="submit" class="btn btn-primary">
		lisa arvustus 
	</a>				   

</div>
<div class="h1">
	kasutajateArvustused
</div>
<div>
	<form method="get">
		<table class="table table-hover">
			<thead>
				<tr>
					<th scope="col">järjekorranumber</th> 
					<th scope="col">CommentID</th> 
					<th scope="col">CommentBody</th> 
					<th scope="col">IsHarmful</th> 
					<th scope="col">CommentCreatedAt</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var comment in Model)
				{
					<tr>
						<td>@rowNumber</td>
						<td>@comment.CommentID</td>
						<td>@comment.CommentBody</td>
						<td>@comment.IsHarmful</td>
						<td>@comment.CommentCreatedAt</td>
						<td>
							<a asp-action="DetailsAdmin" asp-controller="UserComments" asp-route="@comment.CommentID" class="btn btn-primary">Details</a>
							<a asp-action="DeleteComment" asp-controller="UserComments" asp-route="@comment.CommentID" class="btn btn-primary">Delete</a>
						</td>
					</tr>
					rowNumber +=  1;
				}
			</tbody>
		 </table>

	</form>
</div>
 

Filminurk/Views/UserComments/new.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}